theme: jekyll-theme-cayman
title: [Seminaire MIP 2021 - Parcours Dat@HDA]
description: [Répertoire regroupant planning, présentations, jeux de données, ressources, etc. utile pour le séminaire des M2 de l'Université Paris Nanterre du 3 au 7 mai 2021, parcours Parcours Dat@HDA piloté par Antoine Courtin]
