theme: jekyll-theme-cayman
title: [Seminaire MIP 2021 - Parcours Dat@HDA]
description: [Répertoire regroupant planning support et ressources utiles pour le séminaire des M2 - Parcours Dat@HDA de l'Université Paris Nanterre du 3 au 7 mai 2021, piloté par Antoine Courtin]
